### ISSUE TITLE
Graphql error

### ISSUE THREAD

**Issue by radhikavm** [uts-cic/tap#101]
For some odd reason I am getting an error when calling Athanor using the following input:

{
  "input": "Thank you for the final change in text. ",
  "input2": "Although I wasn't certain, I did believe that I was doing the right thing. Next time I will be sure."
}

output:
{
  "data": null,
  "errors": [
    {
      "message": "Internal server error",
      "path": [
        "moves"
      ],
      "locations": [
        {
          "line": 78,
          "column": 3
        }
      ]
    }
  ]
}

Can't see anything obviously wrong in the input, unless I have missed out something obvious.

**Comment by radhikavm** [comment]
Gather Athanor- (http://tap-test.utscic.edu.au/graphiql) is down but rest seem to work as usual.

**Comment by andrewresearch** [comment]
This is fixed in the latest release
