### ISSUE TITLE
Athanor server URL needs to be set in application.conf

### ISSUE THREAD

**Issue by andrewresearch** [uts-cic/tap#108]

**Comment by andrewresearch** [comment]
Use Play config approach to read the URL string of the athanor server from the application.conf file, and make this value by dependency injection in the AthanorClient class.

Suggest config arrangement like:

```
external.servers {
    athanor="http://athanor.server.url/"
}
```

**Comment by quanie** [comment]
Where should I put my new ConfigLoader.scala in the project tree?

**Comment by andrewresearch** [comment]
In the util directory
