### ISSUE TITLE
Add a health enpoint

### ISSUE THREAD

**Issue by andrewresearch** [uts-cic/tap#24]
Need a health endpoint that responds with a status 200 and basic json:

```json
{
  "message": "ok"
}
```

**Comment by radhikavm** [comment]
Sorry just had a quick question, I have integrated http://tap-test.utscic.edu.au/health into AWA3 what's the fall back error for this call, like if its all good & functional the response will be 
{"message", "ok" }
but incase of failure what would be the output of this call? 
I would check the status code on the call and incase of failure just respond as error,  is that a correct assumption?
OR will this be updated to something generic like:

{ "status","ok", " error", []} 
& 
{"status", "failed", "error", ["feature1 unavailable", "Athanor response failed"]}

**Comment by radhikavm** [comment]
Sorry just had a quick question, I have integrated http://tap-test.utscic.edu.au/health into AWA3 what's the fall back error for this call, like if its all good & functional the response will be 
{"message", "ok" }
but incase of failure what would be the output of this call? 
I would check the status code on the call and incase of failure just respond as error,  is that a correct assumption?
OR will this be updated to something generic like:

{ "status","ok", " error", []} 
& 
{"status", "failed", "error", ["feature1 unavailable", "Athanor response failed"]}

**Comment by andrewresearch** [comment]
I would check Status code  and ```{"message", "ok" }```. If status code is not ```200``` then you will not receive the message, so you would then need to look at returned status codes and accompanying error messages such as ```500 Internal Server Error``` or ```400 Bad request``` etc...

**Comment by radhikavm** [comment]
Sure thanks, will do.
