### ISSUE TITLE
Add query time to analytics results

### ISSUE THREAD

**Issue by andrewresearch** [uts-cic/tap#30]

**Comment by quanie** [comment]
Is query time the starting time or the processing time?

**Comment by andrewresearch** [comment]
The processing time. Should be able to do this with System.currentTimeMillis()

**Comment by quanie** [comment]
It should be (end time - start time), shouldn't it? If so, the start time has to be inputted along with the query?

**Comment by andrewresearch** [comment]
Yes, record the start time before the analysis, get the end time after the analysis, and add it to the `Result` object before it is returned by the GraphQL Controller.

**Comment by quanie** [comment]
I have a problem with accessing fields of the `Result` object.

**Comment by andrewresearch** [comment]
You don't access the `Result` object directly as it is a trait. My suggestion is to implemented it as a function that accepts another function as an argument and returns the appropriate result including the timing.
For example if the original function was `analyseString(myString:String):StringResult` then instead of calling this, we would do something like...

```scala
val origFunction = analyseString(myString:String):StringResult

def timedQuery(text:String, analysisFunction:(String) => StringResult):Result = {
  val startTime = System.currentTimeMillis
  val result = analysisFunction(text)
  val queryTime = System.currentTimeMillis - startTime
 // Copy the result object and add in the queryTimeValue here
 // Return the new result
}

// Where the original function was called, we wrap it in the timeQuery function like this...

val newResult = timedQuery(text, origFunction)
```

**Comment by quanie** [comment]
I tried to write a function similar to timedQuery but with different types such as StringResult, SentencesResult, .... However, I was not successful. So this version has some duplicated codes for different case classes.

**Comment by andrewresearch** [comment]
See comment in PR.
