### ISSUE TITLE
Add moves unit and integration tests

### ISSUE THREAD

**Issue by andrewresearch** [uts-cic/tap#51]
This can be copied from athanor server, but also need to include basic connection integration tests

**Comment by quanie** [comment]
What is the moves unit in athanor server? I looked at athanor server source code but I could not figure it out.

**Comment by andrewresearch** [comment]
Check out the GraphiQL query to get an idea of what is returned from athanor-server...

```
query RhetoricalMoves($input: String!) {
  moves(text:$input,grammar:"analytic") {
    analytics
    message
    timestamp
    querytime
  }
}
```
